import { describe, it, expect, beforeEach } from 'vitest';
import mermaid from '../../mermaid.js';

describe('Flowchart Accessibility', () => {
  beforeEach(() => {
    mermaid.initialize({
      startOnLoad: false,
    });
    document.body.innerHTML = '';
    // Mock getBBox for SVG elements
    Object.defineProperty(SVGElement.prototype, 'getBBox', {
      writable: true,
      value: () => ({
        x: 0,
        y: 0,
        width: 10,
        height: 10,
        top: 0,
        right: 10,
        bottom: 10,
        left: 0,
      }),
    });
  });

  const renderDiagram = async (code: string) => {
    const { svg } = await mermaid.render('diagram', code);
    const div = document.createElement('div');
    div.innerHTML = svg;
    document.body.appendChild(div);
    return div;
  };

  it('should have role="list" on nodes container', async () => {
    await renderDiagram(`
      flowchart TD
        A
    `);
    const nodesGroup = document.querySelector('.nodes');
    expect(nodesGroup?.getAttribute('role')).toBe('list');
  });

  it('should have role="listitem" on node containers', async () => {
    await renderDiagram(`
      flowchart TD
        A
    `);
    // The list item is the wrapper around the .node element
    const nodeItem = document.querySelector('g[role="listitem"] > .node');
    expect(nodeItem).not.toBeNull();
    const listItem = nodeItem?.parentElement;
    expect(listItem?.getAttribute('role')).toBe('listitem');
  });

  it('should have aria-labelledby on node pointing to label', async () => {
    await renderDiagram(`
      flowchart TD
        A
    `);
    const nodeItem = document.querySelector('g[role="listitem"] > .node');
    const listItem = nodeItem?.parentElement;
    const labelId = listItem?.getAttribute('aria-labelledby');
    expect(labelId).toBeTruthy();

    const labelGroup = document.getElementById(labelId!);
    expect(labelGroup).not.toBeNull();
    expect(labelGroup?.textContent).toContain('A');
    expect(labelGroup?.getAttribute('aria-hidden')).toBe('true');
  });

  it('should have visually hidden links for edges', async () => {
    await renderDiagram(`
      flowchart TD
        A --> B
    `);

    // Find node A
    const listItems = document.querySelectorAll('g[role="listitem"]');
    let nodeAWrapper;
    for (const item of listItems) {
      if (item.textContent?.includes('A')) {
        nodeAWrapper = item;
        break;
      }
    }

    expect(nodeAWrapper).toBeDefined();

    // Check for hidden link
    const link = nodeAWrapper?.querySelector('a.visually-hidden');
    expect(link).not.toBeNull();
    expect(link?.textContent).toContain('Link to B');

    // Verify target ID
    const href = link?.getAttribute('href');
    expect(href?.startsWith('#')).toBe(true);
  });

  it('should handle subgraphs correctly', async () => {
     await renderDiagram(`
      flowchart TD
        subgraph S1
          A
        end
    `);

    // In Dagre, clusters are siblings to nodes, but both are inside role="list"
    // The cluster itself has role="listitem" in our implementation
    const cluster = document.querySelector('.cluster[role="listitem"]');
    expect(cluster).not.toBeNull();

    const labelId = cluster?.getAttribute('aria-labelledby');
    expect(labelId).toBeTruthy();
    const label = document.getElementById(labelId!);
    expect(label?.textContent).toContain('S1');
    expect(label?.getAttribute('aria-hidden')).toBe('true');
  });

  it('should hide edges from accessibility tree', async () => {
    await renderDiagram(`
      flowchart TD
        A --> B
    `);
    const edgePaths = document.querySelector('.edgePaths');
    const edgeLabels = document.querySelector('.edgeLabels');

    expect(edgePaths?.getAttribute('aria-hidden')).toBe('true');
    expect(edgeLabels?.getAttribute('aria-hidden')).toBe('true');
  });

  it('should have correct nodes in subgraphs', async () => {
    await renderDiagram(`
      flowchart TD
        subgraph S1
          A
        end
        subgraph S2
          B
        end
    `);

    const s1 = document.getElementById('S1');
    const s2 = document.getElementById('S2');

    expect(s1).not.toBeNull();
    expect(s2).not.toBeNull();

    // In the Dagre renderer structure:
    // .root -> .clusters -> .cluster (S1)
    // .root -> .nodes -> .node (A)
    //
    // However, if recursive rendering is working as expected for accessibility grouping,
    // we ideally want the node to be inside the subgraph's list.
    //
    // Let's inspect the actual DOM structure generated by the current recursiveRender implementation.
    // Based on `recursiveRender`:
    // const nodes = elem.insert('g').attr('class', 'nodes');
    // ... insertNode(nodes, ...)
    //
    // If it's recursive, S1 (cluster) should create a new root, which has its own .nodes group containing A.

    // Find the wrapper for S1 (which is the cluster rect/label group)
    // The recursive structure puts children *inside* the cluster group created by recursiveRender?
    // No, `insertCluster` just draws the rect.
    //
    // Let's look for the text "A" and see if it's a descendant of the group that contains S1 label?
    // Actually, looking at `recursiveRender` in `dagre/index.js`:
    // It creates `g.root` -> `g.nodes` (for children).
    // If S1 is a cluster node, it calls `recursiveRender`.
    // So A should be inside a `.nodes` group that is inside the `g` returned by `recursiveRender`.
    // And that `g` is appended to the parent's `.nodes` group.

    // So structure should be:
    // Root .nodes
    //   -> S1 Group (from recursiveRender)
    //      -> .nodes (child list)
    //         -> A (listitem)

    // Find S1's list of nodes
    // The cluster element itself (rect+label) is separate from the container of its children in some logic,
    // but `recursiveRender` returns `elem` which is the root of the subgraph.
    // Let's find where A is.

    const nodeA = Array.from(document.querySelectorAll('.node')).find(n => n.textContent?.includes('A'));
    const nodeB = Array.from(document.querySelectorAll('.node')).find(n => n.textContent?.includes('B'));

    expect(nodeA).toBeDefined();
    expect(nodeB).toBeDefined();

    // Traverse up from A to find the list that contains it
    const listA = nodeA!.closest('[role="list"]');
    // Traverse up from B
    const listB = nodeB!.closest('[role="list"]');

    expect(listA).not.toBeNull();
    expect(listB).not.toBeNull();

    // They should be different lists (or at least different scopes if strictly nested)
    // In this simple case, S1 and S2 are siblings.
    // listA should be the .nodes element inside S1's recursive structure.
    // listB should be the .nodes element inside S2's recursive structure.

    expect(listA).not.toBe(listB);

    // Verify A is not in list B and vice versa
    expect(listA!.contains(nodeB!)).toBe(false);
    expect(listB!.contains(nodeA!)).toBe(false);
  });
});
